# Stocks
#
# <h3>Authentication</h3>                     You need to authenticate to use this API.                     To authenticate click on the \"Authorize\" button and do one of the following steps.<br />                     1. Send your API key in the headers of the request by typing \"Bearer my-key\" on the Bearer authorization scheme.<br />                     2. Send your API key on the \"ApiKey\" query string parameter. To do this type your API key in the Query String authorization scheme.<br />                     Both methods are equally valid. We offer both options so that you can use the method that is easier to use in your application.<br />                     <br />                     <h3>API limits</h3>                     Your API key may be subject to daily/hourly limits. To know how much requests you have left look at the following headers in the response.<br />                     1. <strong>x-ratelimit-limit</strong> - The total number of requests that you are allowed to make in a given period (hour/day)                       2. <strong>x-ratelimit-remaining</strong> - The number of remaining requests that you can perform in the current period.<br />                     3. <strong>x-ratelimit-reset</strong> - The number of seconds until the current period resets.<br />                     <br />                     <h3>Suggestions</h3>                     You don't need to implement the whole API by hand in your programming language of choice.<br />                     Since this API has an OpenAPI specification you can use                      <a href=\"https://github.com/swagger-api/swagger-codegen\" target=\"_blank\">Swagger Generator</a>                      to automatically generate client stubs for more than 30 programming languages.                     <br />                     <br />                     You don't have an API key? <a href=\"https://www.equibles.com/api/pricing\" target=\"_blank\">Get one for free here.</a>
#
# OpenAPI spec version: v1
# Contact: equibles@gmail.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' CommonStock Class
#'
#' @field logo 
#' @field address 
#' @field cik 
#' @field locale 
#' @field marketCap 
#' @field sharesOutstandingLast 
#' @field phoneNumber 
#' @field description 
#' @field employees 
#' @field delisted 
#' @field listDate 
#' @field website 
#' @field industry 
#' @field officers 
#' @field ticker 
#' @field fullTicker 
#' @field assetType 
#' @field name 
#' @field exchange 
#' @field lastPrice 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CommonStock <- R6::R6Class(
  'CommonStock',
  public = list(
    `logo` = NULL,
    `address` = NULL,
    `cik` = NULL,
    `locale` = NULL,
    `marketCap` = NULL,
    `sharesOutstandingLast` = NULL,
    `phoneNumber` = NULL,
    `description` = NULL,
    `employees` = NULL,
    `delisted` = NULL,
    `listDate` = NULL,
    `website` = NULL,
    `industry` = NULL,
    `officers` = NULL,
    `ticker` = NULL,
    `fullTicker` = NULL,
    `assetType` = NULL,
    `name` = NULL,
    `exchange` = NULL,
    `lastPrice` = NULL,
    initialize = function(`logo`, `address`, `cik`, `locale`, `marketCap`, `sharesOutstandingLast`, `phoneNumber`, `description`, `employees`, `delisted`, `listDate`, `website`, `industry`, `officers`, `ticker`, `fullTicker`, `assetType`, `name`, `exchange`, `lastPrice`){
      if (!missing(`logo`)) {
        stopifnot(R6::is.R6(`logo`))
        self$`logo` <- `logo`
      }
      if (!missing(`address`)) {
        stopifnot(is.character(`address`), length(`address`) == 1)
        self$`address` <- `address`
      }
      if (!missing(`cik`)) {
        stopifnot(is.character(`cik`), length(`cik`) == 1)
        self$`cik` <- `cik`
      }
      if (!missing(`locale`)) {
        stopifnot(is.character(`locale`), length(`locale`) == 1)
        self$`locale` <- `locale`
      }
      if (!missing(`marketCap`)) {
        stopifnot(is.numeric(`marketCap`), length(`marketCap`) == 1)
        self$`marketCap` <- `marketCap`
      }
      if (!missing(`sharesOutstandingLast`)) {
        stopifnot(is.numeric(`sharesOutstandingLast`), length(`sharesOutstandingLast`) == 1)
        self$`sharesOutstandingLast` <- `sharesOutstandingLast`
      }
      if (!missing(`phoneNumber`)) {
        stopifnot(is.character(`phoneNumber`), length(`phoneNumber`) == 1)
        self$`phoneNumber` <- `phoneNumber`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`employees`)) {
        stopifnot(is.numeric(`employees`), length(`employees`) == 1)
        self$`employees` <- `employees`
      }
      if (!missing(`delisted`)) {
        self$`delisted` <- `delisted`
      }
      if (!missing(`listDate`)) {
        stopifnot(is.character(`listDate`), length(`listDate`) == 1)
        self$`listDate` <- `listDate`
      }
      if (!missing(`website`)) {
        stopifnot(is.character(`website`), length(`website`) == 1)
        self$`website` <- `website`
      }
      if (!missing(`industry`)) {
        stopifnot(R6::is.R6(`industry`))
        self$`industry` <- `industry`
      }
      if (!missing(`officers`)) {
        stopifnot(is.list(`officers`), length(`officers`) != 0)
        lapply(`officers`, function(x) stopifnot(R6::is.R6(x)))
        self$`officers` <- `officers`
      }
      if (!missing(`ticker`)) {
        stopifnot(is.character(`ticker`), length(`ticker`) == 1)
        self$`ticker` <- `ticker`
      }
      if (!missing(`fullTicker`)) {
        stopifnot(is.character(`fullTicker`), length(`fullTicker`) == 1)
        self$`fullTicker` <- `fullTicker`
      }
      if (!missing(`assetType`)) {
        stopifnot(R6::is.R6(`assetType`))
        self$`assetType` <- `assetType`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`exchange`)) {
        stopifnot(R6::is.R6(`exchange`))
        self$`exchange` <- `exchange`
      }
      if (!missing(`lastPrice`)) {
        stopifnot(R6::is.R6(`lastPrice`))
        self$`lastPrice` <- `lastPrice`
      }
    },
    toJSON = function() {
      CommonStockObject <- list()
      if (!is.null(self$`logo`)) {
        CommonStockObject[['logo']] <- self$`logo`$toJSON()
      }
      if (!is.null(self$`address`)) {
        CommonStockObject[['address']] <- self$`address`
      }
      if (!is.null(self$`cik`)) {
        CommonStockObject[['cik']] <- self$`cik`
      }
      if (!is.null(self$`locale`)) {
        CommonStockObject[['locale']] <- self$`locale`
      }
      if (!is.null(self$`marketCap`)) {
        CommonStockObject[['marketCap']] <- self$`marketCap`
      }
      if (!is.null(self$`sharesOutstandingLast`)) {
        CommonStockObject[['sharesOutstandingLast']] <- self$`sharesOutstandingLast`
      }
      if (!is.null(self$`phoneNumber`)) {
        CommonStockObject[['phoneNumber']] <- self$`phoneNumber`
      }
      if (!is.null(self$`description`)) {
        CommonStockObject[['description']] <- self$`description`
      }
      if (!is.null(self$`employees`)) {
        CommonStockObject[['employees']] <- self$`employees`
      }
      if (!is.null(self$`delisted`)) {
        CommonStockObject[['delisted']] <- self$`delisted`
      }
      if (!is.null(self$`listDate`)) {
        CommonStockObject[['listDate']] <- self$`listDate`
      }
      if (!is.null(self$`website`)) {
        CommonStockObject[['website']] <- self$`website`
      }
      if (!is.null(self$`industry`)) {
        CommonStockObject[['industry']] <- self$`industry`$toJSON()
      }
      if (!is.null(self$`officers`)) {
        CommonStockObject[['officers']] <- lapply(self$`officers`, function(x) x$toJSON())
      }
      if (!is.null(self$`ticker`)) {
        CommonStockObject[['ticker']] <- self$`ticker`
      }
      if (!is.null(self$`fullTicker`)) {
        CommonStockObject[['fullTicker']] <- self$`fullTicker`
      }
      if (!is.null(self$`assetType`)) {
        CommonStockObject[['assetType']] <- self$`assetType`$toJSON()
      }
      if (!is.null(self$`name`)) {
        CommonStockObject[['name']] <- self$`name`
      }
      if (!is.null(self$`exchange`)) {
        CommonStockObject[['exchange']] <- self$`exchange`$toJSON()
      }
      if (!is.null(self$`lastPrice`)) {
        CommonStockObject[['lastPrice']] <- self$`lastPrice`$toJSON()
      }

      CommonStockObject
    },
    fromJSON = function(CommonStockJson) {
      CommonStockObject <- jsonlite::fromJSON(CommonStockJson)
      if (!is.null(CommonStockObject$`logo`)) {
        logoObject <- Image$new()
        logoObject$fromJSON(jsonlite::toJSON(CommonStockObject$logo, auto_unbox = TRUE))
        self$`logo` <- logoObject
      }
      if (!is.null(CommonStockObject$`address`)) {
        self$`address` <- CommonStockObject$`address`
      }
      if (!is.null(CommonStockObject$`cik`)) {
        self$`cik` <- CommonStockObject$`cik`
      }
      if (!is.null(CommonStockObject$`locale`)) {
        self$`locale` <- CommonStockObject$`locale`
      }
      if (!is.null(CommonStockObject$`marketCap`)) {
        self$`marketCap` <- CommonStockObject$`marketCap`
      }
      if (!is.null(CommonStockObject$`sharesOutstandingLast`)) {
        self$`sharesOutstandingLast` <- CommonStockObject$`sharesOutstandingLast`
      }
      if (!is.null(CommonStockObject$`phoneNumber`)) {
        self$`phoneNumber` <- CommonStockObject$`phoneNumber`
      }
      if (!is.null(CommonStockObject$`description`)) {
        self$`description` <- CommonStockObject$`description`
      }
      if (!is.null(CommonStockObject$`employees`)) {
        self$`employees` <- CommonStockObject$`employees`
      }
      if (!is.null(CommonStockObject$`delisted`)) {
        self$`delisted` <- CommonStockObject$`delisted`
      }
      if (!is.null(CommonStockObject$`listDate`)) {
        self$`listDate` <- CommonStockObject$`listDate`
      }
      if (!is.null(CommonStockObject$`website`)) {
        self$`website` <- CommonStockObject$`website`
      }
      if (!is.null(CommonStockObject$`industry`)) {
        industryObject <- Industry$new()
        industryObject$fromJSON(jsonlite::toJSON(CommonStockObject$industry, auto_unbox = TRUE))
        self$`industry` <- industryObject
      }
      if (!is.null(CommonStockObject$`officers`)) {
        self$`officers` <- lapply(CommonStockObject$`officers`, function(x) {
          officersObject <- Officer$new()
          officersObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          officersObject
        })
      }
      if (!is.null(CommonStockObject$`ticker`)) {
        self$`ticker` <- CommonStockObject$`ticker`
      }
      if (!is.null(CommonStockObject$`fullTicker`)) {
        self$`fullTicker` <- CommonStockObject$`fullTicker`
      }
      if (!is.null(CommonStockObject$`assetType`)) {
        assetTypeObject <- AssetType$new()
        assetTypeObject$fromJSON(jsonlite::toJSON(CommonStockObject$assetType, auto_unbox = TRUE))
        self$`assetType` <- assetTypeObject
      }
      if (!is.null(CommonStockObject$`name`)) {
        self$`name` <- CommonStockObject$`name`
      }
      if (!is.null(CommonStockObject$`exchange`)) {
        exchangeObject <- Exchange$new()
        exchangeObject$fromJSON(jsonlite::toJSON(CommonStockObject$exchange, auto_unbox = TRUE))
        self$`exchange` <- exchangeObject
      }
      if (!is.null(CommonStockObject$`lastPrice`)) {
        lastPriceObject <- Price$new()
        lastPriceObject$fromJSON(jsonlite::toJSON(CommonStockObject$lastPrice, auto_unbox = TRUE))
        self$`lastPrice` <- lastPriceObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "logo": %s,
           "address": %s,
           "cik": %s,
           "locale": %s,
           "marketCap": %d,
           "sharesOutstandingLast": %d,
           "phoneNumber": %s,
           "description": %s,
           "employees": %d,
           "delisted": %s,
           "listDate": %s,
           "website": %s,
           "industry": %s,
           "officers": [%s],
           "ticker": %s,
           "fullTicker": %s,
           "assetType": %s,
           "name": %s,
           "exchange": %s,
           "lastPrice": %s
        }',
        self$`logo`$toJSON(),
        self$`address`,
        self$`cik`,
        self$`locale`,
        self$`marketCap`,
        self$`sharesOutstandingLast`,
        self$`phoneNumber`,
        self$`description`,
        self$`employees`,
        self$`delisted`,
        self$`listDate`,
        self$`website`,
        self$`industry`$toJSON(),
        lapply(self$`officers`, function(x) paste(x$toJSON(), sep=",")),
        self$`ticker`,
        self$`fullTicker`,
        self$`assetType`$toJSON(),
        self$`name`,
        self$`exchange`$toJSON(),
        self$`lastPrice`$toJSON()
      )
    },
    fromJSONString = function(CommonStockJson) {
      CommonStockObject <- jsonlite::fromJSON(CommonStockJson)
      ImageObject <- Image$new()
      self$`logo` <- ImageObject$fromJSON(jsonlite::toJSON(CommonStockObject$logo, auto_unbox = TRUE))
      self$`address` <- CommonStockObject$`address`
      self$`cik` <- CommonStockObject$`cik`
      self$`locale` <- CommonStockObject$`locale`
      self$`marketCap` <- CommonStockObject$`marketCap`
      self$`sharesOutstandingLast` <- CommonStockObject$`sharesOutstandingLast`
      self$`phoneNumber` <- CommonStockObject$`phoneNumber`
      self$`description` <- CommonStockObject$`description`
      self$`employees` <- CommonStockObject$`employees`
      self$`delisted` <- CommonStockObject$`delisted`
      self$`listDate` <- CommonStockObject$`listDate`
      self$`website` <- CommonStockObject$`website`
      IndustryObject <- Industry$new()
      self$`industry` <- IndustryObject$fromJSON(jsonlite::toJSON(CommonStockObject$industry, auto_unbox = TRUE))
      self$`officers` <- lapply(CommonStockObject$`officers`, function(x) Officer$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`ticker` <- CommonStockObject$`ticker`
      self$`fullTicker` <- CommonStockObject$`fullTicker`
      AssetTypeObject <- AssetType$new()
      self$`assetType` <- AssetTypeObject$fromJSON(jsonlite::toJSON(CommonStockObject$assetType, auto_unbox = TRUE))
      self$`name` <- CommonStockObject$`name`
      ExchangeObject <- Exchange$new()
      self$`exchange` <- ExchangeObject$fromJSON(jsonlite::toJSON(CommonStockObject$exchange, auto_unbox = TRUE))
      PriceObject <- Price$new()
      self$`lastPrice` <- PriceObject$fromJSON(jsonlite::toJSON(CommonStockObject$lastPrice, auto_unbox = TRUE))
    }
  )
)
